FROM node:latest AS builder

WORKDIR /app
COPY ./admin-panel .
RUN yarn install && yarn build

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/dist ./dist
