FROM node:latest AS builder

WORKDIR /app
COPY ./admin-panel .
RUN yarn install && yarn build

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=builder /app/dist .
COPY nginx.conf /etc/nginx/nginx.conf
