version: '3.3'

services:
  vue:
    hostname: vue
    image: 'node'
    volumes:
      - type: bind
        source: ./admin-panel
        target: /app
        volume:
          nocopy: true
    working_dir: /app
    command: ['yarn', 'dev']
  nginx:
    hostname: nginx
    build: ./nginx
    ports:
      - 8000:80
      - 8443:443
    volumes:
      # - ./admin-panel:/usr/share/nginx/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/ssl/private
      - type: bind
        source: ./admin-panel
        target: /usr/share/nginx/html
        volume:
          nocopy: true
    depends_on:
      - "api"
      - "vue"
  api:
    hostname: api
    build: './api'
    volumes:
      # for development
      - ./api/:/app
    environment:
      NODE_ENV: "development"
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    # ports:
    #   - "8000:8000"
    depends_on:
      - "mongodb"
    #restart: always
    command: ["yarn", "dev"]

  mongodb:
    image: mongo
    restart: always
    volumes:
      - type: volume
        source: dbdata
        target: /data/db
        volume:
          nocopy: true
    environment:
      # for production we can use _FILE variables and docker secrets
      # https://hub.docker.com/_/mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  dbdata:
  admin-panel:
  # neo4j:
  #   image: "neo4j:4.0.3"
  #   ports:
  #     - "7474:7474"
  #     - "7687:7687"
  #   environment:
  #     # dev only!
  #     NEO4J_AUTH: "none"
