version: '3'

services:
  api:
    build: './api'
    volumes:
      # for development
      - ./api/:/app
    environment:
      NODE_ENV: "development"
    ports:
      - "8000:80"
    depends_on:
      - "database"
    command: ["yarn", "start"]

  database:
    image: "neo4j:4.0.3"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      # dev only!
      NEO4J_AUTH: "none"
