version: '3.3'

services:
  api:
    build: './api'
    volumes:
      # for development
      - ./api/:/app
    environment:
      NODE_ENV: "development"
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "8000:8000"
    depends_on:
      - "mongodb"
    #restart: always
    command: ["yarn", "dev"]

  mongodb:
    image: mongo
    restart: always
    volumes:
      - type: volume
        source: dbdata
        target: /data/db
        volume:
          nocopy: true
    environment:
      # for production we can use _FILE variables and docker secrets
      # https://hub.docker.com/_/mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  dbdata:

  # neo4j:
  #   image: "neo4j:4.0.3"
  #   ports:
  #     - "7474:7474"
  #     - "7687:7687"
  #   environment:
  #     # dev only!
  #     NEO4J_AUTH: "none"
