version: '3'

services:
  api:
    build: './api'
    volumes:
      # for development
      - ./api/:/app
    environment:
      NODE_ENV: "development"
      NEO4J_PORT: "7687"
    ports:
      - "8000:8000"
    depends_on:
      - "neo4j"
    command: ["yarn", "dev"]

  neo4j:
    image: "neo4j:4.0.3"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      # dev only!
      NEO4J_AUTH: "none"
